/**
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

import type { EsApiDefinition } from '../types.ts'

/** shared query params that appear on nearly every cat API */
const catCommon = [
  { name: 'v', type: 'boolean' as const, description: 'Include column headings in the output' },
  { name: 'format', cliFlag: 'response-format', type: 'string' as const, description: 'Response format (text, json, yaml, cbor, smile)' },
  { name: 'h', type: 'string' as const, description: 'Comma-separated list of column names to display' },
  { name: 's', type: 'string' as const, description: 'Comma-separated list of column names used to sort' },
]

export const catApis: EsApiDefinition[] = [
  {
    name: 'aliases',
    namespace: 'cat',
    description: "Returns the cluster's index aliases",
    method: 'GET',
    path: '/_cat/aliases/{name}',
    pathParams: [{ name: 'name', description: 'Comma-separated list of alias names', required: false }],
    queryParams: [
      ...catCommon,
      { name: 'expand_wildcards', type: 'string', description: 'Type of index that wildcard patterns can match' },
    ],
    responseType: 'text',
  },
  {
    name: 'allocation',
    namespace: 'cat',
    description: 'Provides a snapshot of the number of shards allocated to each data node',
    method: 'GET',
    path: '/_cat/allocation/{node_id}',
    pathParams: [{ name: 'node_id', description: 'Comma-separated list of node IDs or names', required: false }],
    queryParams: [
      ...catCommon,
      { name: 'bytes', type: 'string', description: 'Unit used to display byte values' },
    ],
    responseType: 'text',
  },
  {
    name: 'component-templates',
    namespace: 'cat',
    description: 'Returns information about component templates',
    method: 'GET',
    path: '/_cat/component_templates/{name}',
    pathParams: [{ name: 'name', description: 'Comma-separated list of component template names', required: false }],
    queryParams: [...catCommon],
    responseType: 'text',
  },
  {
    name: 'count',
    namespace: 'cat',
    description: 'Provides quick access to the document count of the entire cluster or an individual index',
    method: 'GET',
    path: '/_cat/count/{index}',
    pathParams: [{ name: 'index', description: 'Comma-separated list of indices', required: false }],
    queryParams: [...catCommon],
    responseType: 'text',
  },
  {
    name: 'fielddata',
    namespace: 'cat',
    description: 'Reports the amount of heap memory currently used by the field data cache',
    method: 'GET',
    path: '/_cat/fielddata/{fields}',
    pathParams: [{ name: 'fields', description: 'Comma-separated list of fields used to limit returned information', required: false }],
    queryParams: [
      ...catCommon,
      { name: 'bytes', type: 'string', description: 'Unit used to display byte values' },
    ],
    responseType: 'text',
  },
  {
    name: 'health',
    namespace: 'cat',
    description: 'Returns the health status of the cluster',
    method: 'GET',
    path: '/_cat/health',
    queryParams: [
      ...catCommon,
      { name: 'ts', type: 'boolean', description: 'Return local time and date instead of epoch' },
    ],
    responseType: 'text',
  },
  {
    name: 'indices',
    namespace: 'cat',
    description: 'Returns high-level information about indices in a cluster',
    method: 'GET',
    path: '/_cat/indices/{index}',
    pathParams: [{ name: 'index', description: 'Comma-separated list of indices', required: false }],
    queryParams: [
      ...catCommon,
      { name: 'health', type: 'string', description: 'Filter by health status (green, yellow, red)' },
      { name: 'pri', type: 'boolean', description: 'Show primary shards only' },
      { name: 'bytes', type: 'string', description: 'Unit used to display byte values' },
      { name: 'expand_wildcards', type: 'string', description: 'Type of index that wildcard patterns can match' },
    ],
    responseType: 'text',
  },
  {
    name: 'master',
    namespace: 'cat',
    description: 'Returns information about the master node',
    method: 'GET',
    path: '/_cat/master',
    queryParams: [...catCommon],
    responseType: 'text',
  },
  {
    name: 'ml-data-frame-analytics',
    namespace: 'cat',
    description: 'Returns configuration and usage information about data frame analytics jobs',
    method: 'GET',
    path: '/_cat/ml/data_frame/analytics/{id}',
    pathParams: [{ name: 'id', description: 'The ID of the data frame analytics to fetch', required: false }],
    queryParams: [
      ...catCommon,
      { name: 'bytes', type: 'string', description: 'Unit used to display byte values' },
    ],
    responseType: 'text',
  },
  {
    name: 'ml-datafeeds',
    namespace: 'cat',
    description: 'Returns configuration and usage information about datafeeds',
    method: 'GET',
    path: '/_cat/ml/datafeeds/{datafeed_id}',
    pathParams: [{ name: 'datafeed_id', description: 'The ID of the datafeed to fetch', required: false }],
    queryParams: [...catCommon],
    responseType: 'text',
  },
  {
    name: 'ml-jobs',
    namespace: 'cat',
    description: 'Returns configuration and usage information about anomaly detection jobs',
    method: 'GET',
    path: '/_cat/ml/anomaly_detectors/{job_id}',
    pathParams: [{ name: 'job_id', description: 'The ID of the anomaly detection job to fetch', required: false }],
    queryParams: [
      ...catCommon,
      { name: 'bytes', type: 'string', description: 'Unit used to display byte values' },
    ],
    responseType: 'text',
  },
  {
    name: 'ml-trained-models',
    namespace: 'cat',
    description: 'Returns configuration and usage information about trained models',
    method: 'GET',
    path: '/_cat/ml/trained_models/{model_id}',
    pathParams: [{ name: 'model_id', description: 'The ID of the trained model to fetch', required: false }],
    queryParams: [
      ...catCommon,
      { name: 'bytes', type: 'string', description: 'Unit used to display byte values' },
    ],
    responseType: 'text',
  },
  {
    name: 'nodeattrs',
    namespace: 'cat',
    description: 'Returns information about custom node attributes',
    method: 'GET',
    path: '/_cat/nodeattrs',
    queryParams: [...catCommon],
    responseType: 'text',
  },
  {
    name: 'nodes',
    namespace: 'cat',
    description: 'Returns information about the nodes in a cluster',
    method: 'GET',
    path: '/_cat/nodes',
    queryParams: [
      ...catCommon,
      { name: 'full_id', type: 'boolean', description: 'Return the full node ID' },
      { name: 'bytes', type: 'string', description: 'Unit used to display byte values' },
    ],
    responseType: 'text',
  },
  {
    name: 'pending-tasks',
    namespace: 'cat',
    description: 'Returns cluster-level changes that have not yet been executed',
    method: 'GET',
    path: '/_cat/pending_tasks',
    queryParams: [...catCommon],
    responseType: 'text',
  },
  {
    name: 'plugins',
    namespace: 'cat',
    description: 'Returns a list of installed plugins for each node',
    method: 'GET',
    path: '/_cat/plugins',
    queryParams: [...catCommon],
    responseType: 'text',
  },
  {
    name: 'recovery',
    namespace: 'cat',
    description: 'Returns information about index shard recoveries',
    method: 'GET',
    path: '/_cat/recovery/{index}',
    pathParams: [{ name: 'index', description: 'Comma-separated list of indices', required: false }],
    queryParams: [
      ...catCommon,
      { name: 'bytes', type: 'string', description: 'Unit used to display byte values' },
      { name: 'active_only', type: 'boolean', description: 'If true, only recoveries that are currently on-going' },
      { name: 'detailed', type: 'boolean', description: 'If true, includes detailed information about shard recoveries' },
    ],
    responseType: 'text',
  },
  {
    name: 'repositories',
    namespace: 'cat',
    description: 'Returns the snapshot repositories for the cluster',
    method: 'GET',
    path: '/_cat/repositories',
    queryParams: [...catCommon],
    responseType: 'text',
  },
  {
    name: 'segments',
    namespace: 'cat',
    description: 'Returns low-level information about the Lucene segments in index shards',
    method: 'GET',
    path: '/_cat/segments/{index}',
    pathParams: [{ name: 'index', description: 'Comma-separated list of indices', required: false }],
    queryParams: [
      ...catCommon,
      { name: 'bytes', type: 'string', description: 'Unit used to display byte values' },
    ],
    responseType: 'text',
  },
  {
    name: 'shards',
    namespace: 'cat',
    description: 'Provides a detailed view of shard allocation across nodes',
    method: 'GET',
    path: '/_cat/shards/{index}',
    pathParams: [{ name: 'index', description: 'Comma-separated list of indices', required: false }],
    queryParams: [
      ...catCommon,
      { name: 'bytes', type: 'string', description: 'Unit used to display byte values' },
    ],
    responseType: 'text',
  },
  {
    name: 'snapshots',
    namespace: 'cat',
    description: 'Returns all snapshots in a specific repository',
    method: 'GET',
    path: '/_cat/snapshots/{repository}',
    pathParams: [{ name: 'repository', description: 'Name of the snapshot repository', required: false }],
    queryParams: [
      ...catCommon,
      { name: 'ignore_unavailable', type: 'boolean', description: 'If true, missing or closed indices are not included in the response' },
    ],
    responseType: 'text',
  },
  {
    name: 'tasks',
    namespace: 'cat',
    description: 'Returns information about tasks currently executing in the cluster',
    method: 'GET',
    path: '/_cat/tasks',
    queryParams: [
      ...catCommon,
      { name: 'nodes', type: 'string', description: 'Comma-separated list of node IDs or names to limit the returned information' },
      { name: 'actions', type: 'string', description: 'Comma-separated list of actions to filter tasks' },
      { name: 'parent_task_id', type: 'string', description: 'Parent task ID used to limit returned information' },
      { name: 'detailed', type: 'boolean', description: 'If true, returns detailed task information' },
    ],
    responseType: 'text',
  },
  {
    name: 'templates',
    namespace: 'cat',
    description: 'Returns information about index templates in a cluster',
    method: 'GET',
    path: '/_cat/templates/{name}',
    pathParams: [{ name: 'name', description: 'Name of the template to retrieve', required: false }],
    queryParams: [...catCommon],
    responseType: 'text',
  },
  {
    name: 'thread-pool',
    namespace: 'cat',
    description: 'Returns thread pool statistics for each node in a cluster',
    method: 'GET',
    path: '/_cat/thread_pool/{thread_pool_patterns}',
    pathParams: [{ name: 'thread_pool_patterns', description: 'Comma-separated list of thread pool names', required: false }],
    queryParams: [...catCommon],
    responseType: 'text',
  },
  {
    name: 'transforms',
    namespace: 'cat',
    description: 'Returns configuration and usage information about transforms',
    method: 'GET',
    path: '/_cat/transforms/{transform_id}',
    pathParams: [{ name: 'transform_id', description: 'The ID of the transform', required: false }],
    queryParams: [
      ...catCommon,
      { name: 'from', type: 'number', description: 'Skips the specified number of transforms' },
      { name: 'size', type: 'number', description: 'Specifies the maximum number of transforms to obtain' },
      { name: 'allow_no_match', type: 'boolean', description: 'If false, the request returns an error if any wildcard expression matches no transforms' },
    ],
    responseType: 'text',
  },
]
