/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { EsApiDefinition } from '../types.ts'

export const fleetMsearchApis: EsApiDefinition[] = [
 {
  name: "msearch",
  namespace: "fleet",
  description: "Run multiple Fleet searches.",
  method: "GET",
  path: "/_fleet/_fleet_msearch",
  bodyFormat: 'ndjson',
 },
]
