/**
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

import { z } from 'zod'
import type { EsApiDefinition } from '../types.ts'

/** shared query params common to many indices APIs */
const withIndex = [{ name: 'index', description: 'Comma-separated list of indices', required: true }] as const
const withOptionalIndex = [{ name: 'index', description: 'Comma-separated list of indices', required: false }] as const
const masterTimeout = { name: 'master_timeout', type: 'string' as const, description: 'Timeout for connection to master node' }
const timeout = { name: 'timeout', type: 'string' as const, description: 'Timeout for the request' }
const waitForActiveShards = { name: 'wait_for_active_shards', type: 'string' as const, description: 'Number of active shards to wait for' }
const ignoreUnavailable = { name: 'ignore_unavailable', type: 'boolean' as const, description: 'Ignore unavailable indices' }
const allowNoIndices = { name: 'allow_no_indices', type: 'boolean' as const, description: 'Allow request if no matching indices found' }
const expandWildcards = { name: 'expand_wildcards', type: 'string' as const, description: 'Type of index that wildcard patterns can match' }

export const indicesApis: EsApiDefinition[] = [
  {
    name: 'add-block',
    namespace: 'indices',
    description: 'Adds a block to an index',
    method: 'PUT',
    path: '/{index}/_block/{block}',
    pathParams: [
      { name: 'index', description: 'Comma-separated list of indices', required: true },
      { name: 'block', description: 'The block type to add (metadata, read, read_only, write)', required: true },
    ],
    queryParams: [masterTimeout, timeout, ignoreUnavailable, allowNoIndices, expandWildcards],
    responseType: 'json',
  },
  {
    name: 'analyze',
    namespace: 'indices',
    description: 'Performs analysis on a text string and returns the resulting tokens',
    method: 'POST',
    path: '/{index}/_analyze',
    pathParams: [{ name: 'index', description: 'Index used to derive the analyzer', required: false }],
    body: z.object({
      analyzer: z.string().optional().describe('The name of the analyzer'),
      text: z.union([z.string(), z.array(z.string())]).optional().describe('Text to analyze'),
      tokenizer: z.string().optional().describe('The name of the tokenizer to use'),
      filter: z.array(z.string()).optional().describe('Array of token filters'),
      char_filter: z.array(z.string()).optional().describe('Array of character filters'),
      field: z.string().optional().describe('Field used to derive the analyzer'),
    }),
    responseType: 'json',
  },
  {
    name: 'clear-cache',
    namespace: 'indices',
    description: 'Clears the caches of one or more indices',
    method: 'POST',
    path: '/{index}/_cache/clear',
    pathParams: [...withOptionalIndex],
    queryParams: [
      ignoreUnavailable, allowNoIndices, expandWildcards,
      { name: 'fielddata', type: 'boolean', description: 'Clear the fielddata cache' },
      { name: 'fields', type: 'string', description: 'Comma-separated list of fields to clear from the fielddata cache' },
      { name: 'query', type: 'boolean', description: 'Clear the query cache' },
      { name: 'request', type: 'boolean', description: 'Clear the request cache' },
    ],
    responseType: 'json',
  },
  {
    name: 'clone',
    namespace: 'indices',
    description: 'Clones an existing index',
    method: 'PUT',
    path: '/{index}/_clone/{target}',
    pathParams: [
      { name: 'index', description: 'Name of the source index', required: true },
      { name: 'target', description: 'Name of the target index', required: true },
    ],
    queryParams: [masterTimeout, timeout, waitForActiveShards],
    body: z.object({
      settings: z.record(z.string(), z.unknown()).optional().describe('Index settings for the target index'),
      aliases: z.record(z.string(), z.unknown()).optional().describe('Aliases for the target index'),
    }),
    responseType: 'json',
  },
  {
    name: 'close',
    namespace: 'indices',
    description: 'Closes an index',
    method: 'POST',
    path: '/{index}/_close',
    pathParams: [...withIndex],
    queryParams: [masterTimeout, timeout, waitForActiveShards, ignoreUnavailable, allowNoIndices, expandWildcards],
    responseType: 'json',
  },
  {
    name: 'create',
    namespace: 'indices',
    description: 'Creates a new index',
    method: 'PUT',
    path: '/{index}',
    pathParams: [...withIndex],
    queryParams: [waitForActiveShards, masterTimeout, timeout],
    body: z.object({
      settings: z.record(z.string(), z.unknown()).optional().describe('Index settings'),
      mappings: z.record(z.string(), z.unknown()).optional().describe('Index mappings'),
      aliases: z.record(z.string(), z.unknown()).optional().describe('Index aliases'),
    }),
    responseType: 'json',
  },
  {
    name: 'delete',
    namespace: 'indices',
    description: 'Deletes one or more indices',
    method: 'DELETE',
    path: '/{index}',
    pathParams: [...withIndex],
    queryParams: [masterTimeout, timeout, ignoreUnavailable, allowNoIndices, expandWildcards],
    responseType: 'json',
  },
  {
    name: 'delete-alias',
    namespace: 'indices',
    description: 'Deletes an alias',
    method: 'DELETE',
    path: '/{index}/_alias/{name}',
    pathParams: [
      { name: 'index', description: 'Comma-separated list of indices', required: true },
      { name: 'name', description: 'Comma-separated list of aliases to delete', required: true },
    ],
    queryParams: [masterTimeout, timeout],
    responseType: 'json',
  },
  {
    name: 'delete-index-template',
    namespace: 'indices',
    description: 'Deletes an index template',
    method: 'DELETE',
    path: '/_index_template/{name}',
    pathParams: [{ name: 'name', description: 'Comma-separated list of index template names', required: true }],
    queryParams: [masterTimeout, timeout],
    responseType: 'json',
  },
  {
    name: 'delete-template',
    namespace: 'indices',
    description: 'Deletes a legacy index template',
    method: 'DELETE',
    path: '/_template/{name}',
    pathParams: [{ name: 'name', description: 'Name of the legacy index template to delete', required: true }],
    queryParams: [masterTimeout, timeout],
    responseType: 'json',
  },
  {
    name: 'exists',
    namespace: 'indices',
    description: 'Returns whether one or more indices exist',
    method: 'HEAD',
    path: '/{index}',
    pathParams: [...withIndex],
    queryParams: [ignoreUnavailable, allowNoIndices, expandWildcards,
      { name: 'flat_settings', type: 'boolean', description: 'Return settings in flat format' },
      { name: 'include_defaults', type: 'boolean', description: 'Include default settings' },
    ],
    responseType: 'json',
  },
  {
    name: 'flush',
    namespace: 'indices',
    description: 'Flushes one or more indices',
    method: 'POST',
    path: '/{index}/_flush',
    pathParams: [...withOptionalIndex],
    queryParams: [
      ignoreUnavailable, allowNoIndices, expandWildcards,
      { name: 'force', type: 'boolean', description: 'Force a flush even if it is not necessary' },
      { name: 'wait_if_ongoing', type: 'boolean', description: 'Block until the flush succeeds if another flush is running' },
    ],
    responseType: 'json',
  },
  {
    name: 'forcemerge',
    namespace: 'indices',
    description: 'Forces a merge on the shards of one or more indices',
    method: 'POST',
    path: '/{index}/_forcemerge',
    pathParams: [...withOptionalIndex],
    queryParams: [
      ignoreUnavailable, allowNoIndices, expandWildcards,
      { name: 'max_num_segments', type: 'number', description: 'Maximum number of segments to merge to' },
      { name: 'only_expunge_deletes', type: 'boolean', description: 'Expunge deleted documents only' },
      { name: 'flush', type: 'boolean', description: 'Flush each index after performing the force merge' },
    ],
    responseType: 'json',
  },
  {
    name: 'get',
    namespace: 'indices',
    description: 'Returns information about one or more indices',
    method: 'GET',
    path: '/{index}',
    pathParams: [...withIndex],
    queryParams: [
      masterTimeout, ignoreUnavailable, allowNoIndices, expandWildcards,
      { name: 'flat_settings', type: 'boolean', description: 'Return settings in flat format' },
      { name: 'include_defaults', type: 'boolean', description: 'Include default settings' },
    ],
    responseType: 'json',
  },
  {
    name: 'get-alias',
    namespace: 'indices',
    description: 'Returns information about one or more aliases',
    method: 'GET',
    path: '/{index}/_alias/{name}',
    pathParams: [
      { name: 'index', description: 'Comma-separated list of indices', required: false },
      { name: 'name', description: 'Comma-separated list of aliases', required: false },
    ],
    queryParams: [ignoreUnavailable, allowNoIndices, expandWildcards],
    responseType: 'json',
  },
  {
    name: 'get-index-template',
    namespace: 'indices',
    description: 'Returns information about one or more index templates',
    method: 'GET',
    path: '/_index_template/{name}',
    pathParams: [{ name: 'name', description: 'Comma-separated list of index template names', required: false }],
    queryParams: [
      masterTimeout,
      { name: 'flat_settings', type: 'boolean', description: 'Return settings in flat format' },
      { name: 'local', type: 'boolean', description: 'Return local information, do not retrieve the state from cluster-manager node' },
    ],
    responseType: 'json',
  },
  {
    name: 'get-mapping',
    namespace: 'indices',
    description: 'Returns mapping definitions for one or more indices',
    method: 'GET',
    path: '/{index}/_mapping',
    pathParams: [...withOptionalIndex],
    queryParams: [masterTimeout, ignoreUnavailable, allowNoIndices, expandWildcards,
      { name: 'local', type: 'boolean', description: 'Return local information only' },
    ],
    responseType: 'json',
  },
  {
    name: 'get-settings',
    namespace: 'indices',
    description: 'Returns setting information for one or more indices',
    method: 'GET',
    path: '/{index}/_settings/{name}',
    pathParams: [
      { name: 'index', description: 'Comma-separated list of indices', required: false },
      { name: 'name', description: 'Comma-separated list of settings to retrieve', required: false },
    ],
    queryParams: [
      masterTimeout, ignoreUnavailable, allowNoIndices, expandWildcards,
      { name: 'flat_settings', type: 'boolean', description: 'Return settings in flat format' },
      { name: 'include_defaults', type: 'boolean', description: 'Include default settings' },
      { name: 'local', type: 'boolean', description: 'Return local information only' },
    ],
    responseType: 'json',
  },
  {
    name: 'get-template',
    namespace: 'indices',
    description: 'Returns information about one or more legacy index templates',
    method: 'GET',
    path: '/_template/{name}',
    pathParams: [{ name: 'name', description: 'Comma-separated list of index template names', required: false }],
    queryParams: [
      masterTimeout,
      { name: 'flat_settings', type: 'boolean', description: 'Return settings in flat format' },
      { name: 'local', type: 'boolean', description: 'Return local information only' },
    ],
    responseType: 'json',
  },
  {
    name: 'open',
    namespace: 'indices',
    description: 'Opens a closed index',
    method: 'POST',
    path: '/{index}/_open',
    pathParams: [...withIndex],
    queryParams: [masterTimeout, timeout, waitForActiveShards, ignoreUnavailable, allowNoIndices, expandWildcards],
    responseType: 'json',
  },
  {
    name: 'put-alias',
    namespace: 'indices',
    description: 'Creates or updates an alias',
    method: 'PUT',
    path: '/{index}/_alias/{name}',
    pathParams: [
      { name: 'index', description: 'Comma-separated list of indices', required: true },
      { name: 'name', description: 'Name of the alias', required: true },
    ],
    queryParams: [masterTimeout, timeout],
    body: z.object({
      filter: z.record(z.string(), z.unknown()).optional().describe('Query used to filter documents the alias applies to'),
      index_routing: z.string().optional().describe('Value used to route indexing operations to a specific shard'),
      is_write_index: z.boolean().optional().describe('If true, sets the write index or data stream for the alias'),
      routing: z.string().optional().describe('Value used to route indexing and search operations to a specific shard'),
      search_routing: z.string().optional().describe('Value used to route search operations to a specific shard'),
    }),
    responseType: 'json',
  },
  {
    name: 'put-index-template',
    namespace: 'indices',
    description: 'Creates or updates an index template',
    method: 'PUT',
    path: '/_index_template/{name}',
    pathParams: [{ name: 'name', description: 'Name of the index template', required: true }],
    queryParams: [masterTimeout],
    body: z.object({
      index_patterns: z.array(z.string()).optional().describe('Array of wildcard expressions to match index names'),
      composed_of: z.array(z.string()).optional().describe('Array of component template names'),
      priority: z.number().optional().describe('Priority to determine index template precedence'),
      template: z.record(z.string(), z.unknown()).optional().describe('Template to be applied'),
      _meta: z.record(z.string(), z.unknown()).optional().describe('Optional user metadata'),
    }),
    responseType: 'json',
  },
  {
    name: 'put-mapping',
    namespace: 'indices',
    description: 'Adds new fields to an existing index or changes the search settings of existing fields',
    method: 'PUT',
    path: '/{index}/_mapping',
    pathParams: [...withIndex],
    queryParams: [masterTimeout, timeout, ignoreUnavailable, allowNoIndices, expandWildcards,
      { name: 'write_index_only', type: 'boolean', description: 'If true, applies mappings only to the write index of an alias or data stream' },
    ],
    body: z.object({
      properties: z.record(z.string(), z.unknown()).optional().describe('Mapping for fields in the index'),
      dynamic: z.union([z.boolean(), z.string()]).optional().describe('Controls whether new fields are added dynamically'),
      _meta: z.record(z.string(), z.unknown()).optional().describe('Optional user metadata'),
    }),
    responseType: 'json',
  },
  {
    name: 'put-settings',
    namespace: 'indices',
    description: 'Changes a dynamic index setting in real time',
    method: 'PUT',
    path: '/{index}/_settings',
    pathParams: [...withOptionalIndex],
    queryParams: [masterTimeout, timeout, ignoreUnavailable, allowNoIndices, expandWildcards,
      { name: 'flat_settings', type: 'boolean', description: 'Return settings in flat format' },
      { name: 'preserve_existing', type: 'boolean', description: 'If true, existing index settings remain unchanged' },
    ],
    // body is free-form key-value (arbitrary index settings); provide via --file or stdin
    responseType: 'json',
  },
  {
    name: 'put-template',
    namespace: 'indices',
    description: 'Creates or updates a legacy index template',
    method: 'PUT',
    path: '/_template/{name}',
    pathParams: [{ name: 'name', description: 'Name of the legacy index template', required: true }],
    queryParams: [masterTimeout, timeout,
      { name: 'create', type: 'boolean', description: 'If true, this request cannot replace or update existing index templates' },
    ],
    body: z.object({
      index_patterns: z.array(z.string()).optional().describe('Array of wildcard expressions to match index names'),
      settings: z.record(z.string(), z.unknown()).optional().describe('Index settings'),
      mappings: z.record(z.string(), z.unknown()).optional().describe('Mapping for fields in the index'),
      aliases: z.record(z.string(), z.unknown()).optional().describe('Index aliases'),
      order: z.number().optional().describe('Order in which to apply this template if multiple match'),
    }),
    responseType: 'json',
  },
  {
    name: 'recovery',
    namespace: 'indices',
    description: 'Returns information about ongoing and completed shard recoveries for one or more indices',
    method: 'GET',
    path: '/{index}/_recovery',
    pathParams: [...withOptionalIndex],
    queryParams: [
      { name: 'bytes', type: 'string', description: 'Unit used to display byte values' },
      { name: 'detailed', type: 'boolean', description: 'If true, include detailed information about shard recoveries' },
      { name: 'active_only', type: 'boolean', description: 'If true, only include ongoing recoveries' },
    ],
    responseType: 'json',
  },
  {
    name: 'refresh',
    namespace: 'indices',
    description: 'Refreshes one or more indices',
    method: 'POST',
    path: '/{index}/_refresh',
    pathParams: [...withOptionalIndex],
    queryParams: [ignoreUnavailable, allowNoIndices, expandWildcards],
    responseType: 'json',
  },
  {
    name: 'resolve-index',
    namespace: 'indices',
    description: 'Returns information about any matching indices, aliases, and data streams',
    method: 'GET',
    path: '/_resolve/index/{name}',
    pathParams: [{ name: 'name', description: 'Comma-separated list of names or wildcard expressions', required: true }],
    queryParams: [expandWildcards],
    responseType: 'json',
  },
  {
    name: 'rollover',
    namespace: 'indices',
    description: 'Creates a new index for a data stream or index alias',
    method: 'POST',
    path: '/{alias}/_rollover/{new_index}',
    pathParams: [
      { name: 'alias', description: 'Name of the data stream or index alias', required: true },
      { name: 'new_index', description: 'Name of the index to create', required: false },
    ],
    queryParams: [masterTimeout, timeout, waitForActiveShards,
      { name: 'dry_run', cliFlag: 'rollover-dry-run', type: 'boolean', description: 'If true, checks whether the current index satisfies the rollover conditions without performing a rollover' },
    ],
    body: z.object({
      conditions: z.record(z.string(), z.unknown()).optional().describe('Conditions for the rollover'),
      mappings: z.record(z.string(), z.unknown()).optional().describe('Mapping for fields in the new index'),
      settings: z.record(z.string(), z.unknown()).optional().describe('Configuration options for the new index'),
      aliases: z.record(z.string(), z.unknown()).optional().describe('Aliases for the new index'),
    }),
    responseType: 'json',
  },
  {
    name: 'segments',
    namespace: 'indices',
    description: 'Returns low-level information about the Lucene segments in index shards',
    method: 'GET',
    path: '/{index}/_segments',
    pathParams: [...withOptionalIndex],
    queryParams: [ignoreUnavailable, allowNoIndices, expandWildcards,
      { name: 'verbose', type: 'boolean', description: 'If true, the request returns a verbose response' },
    ],
    responseType: 'json',
  },
  {
    name: 'shard-stores',
    namespace: 'indices',
    description: 'Retrieves store information about replica shards in one or more indices',
    method: 'GET',
    path: '/{index}/_shard_stores',
    pathParams: [...withOptionalIndex],
    queryParams: [ignoreUnavailable, allowNoIndices, expandWildcards,
      { name: 'status', type: 'string', description: 'List of shard health statuses used to limit the request (green, yellow, red, all)' },
    ],
    responseType: 'json',
  },
  {
    name: 'shrink',
    namespace: 'indices',
    description: 'Shrinks an existing index into a new index with fewer primary shards',
    method: 'PUT',
    path: '/{index}/_shrink/{target}',
    pathParams: [
      { name: 'index', description: 'Name of the source index', required: true },
      { name: 'target', description: 'Name of the target index', required: true },
    ],
    queryParams: [masterTimeout, timeout, waitForActiveShards],
    body: z.object({
      settings: z.record(z.string(), z.unknown()).optional().describe('Index settings for the target index'),
      aliases: z.record(z.string(), z.unknown()).optional().describe('Aliases for the target index'),
    }),
    responseType: 'json',
  },
  {
    name: 'simulate-index-template',
    namespace: 'indices',
    description: 'Simulates the index settings, mappings, and aliases that would be applied to the specified index name by the existing index templates',
    method: 'POST',
    path: '/_index_template/_simulate_index/{name}',
    pathParams: [{ name: 'name', description: 'Name of the index to simulate', required: true }],
    queryParams: [masterTimeout],
    responseType: 'json',
  },
  {
    name: 'simulate-template',
    namespace: 'indices',
    description: 'Simulates resolving the given template name or definition',
    method: 'POST',
    path: '/_index_template/_simulate/{name}',
    pathParams: [{ name: 'name', description: 'Name of the index template to simulate', required: false }],
    queryParams: [masterTimeout],
    body: z.object({
      index_patterns: z.array(z.string()).optional().describe('Array of wildcard expressions to match index names'),
      composed_of: z.array(z.string()).optional().describe('Array of component template names'),
      priority: z.number().optional().describe('Priority to determine template precedence'),
      template: z.record(z.string(), z.unknown()).optional().describe('Template to be applied'),
    }),
    responseType: 'json',
  },
  {
    name: 'split',
    namespace: 'indices',
    description: 'Splits an existing index into a new index with more primary shards',
    method: 'PUT',
    path: '/{index}/_split/{target}',
    pathParams: [
      { name: 'index', description: 'Name of the source index', required: true },
      { name: 'target', description: 'Name of the target index', required: true },
    ],
    queryParams: [masterTimeout, timeout, waitForActiveShards],
    body: z.object({
      settings: z.record(z.string(), z.unknown()).optional().describe('Index settings for the target index'),
      aliases: z.record(z.string(), z.unknown()).optional().describe('Aliases for the target index'),
    }),
    responseType: 'json',
  },
  {
    name: 'stats',
    namespace: 'indices',
    description: 'Returns statistics for one or more indices',
    method: 'GET',
    path: '/{index}/_stats/{metric}',
    pathParams: [
      { name: 'index', description: 'Comma-separated list of indices', required: false },
      { name: 'metric', description: 'Comma-separated list of stats to retrieve', required: false },
    ],
    queryParams: [ignoreUnavailable, allowNoIndices, expandWildcards,
      { name: 'completion_fields', type: 'string', description: 'Comma-separated list of fields for fielddata and suggest index metric' },
      { name: 'fielddata_fields', type: 'string', description: 'Comma-separated list of fields for fielddata index metric' },
      { name: 'fields', type: 'string', description: 'Comma-separated list of fields for fielddata and completion index metrics' },
      { name: 'level', type: 'string', description: 'Indicates whether statistics are aggregated at the cluster, index, or shard level' },
      { name: 'include_segment_file_sizes', type: 'boolean', description: 'If true, the call reports the aggregated disk usage of each one of the Lucene index files' },
    ],
    responseType: 'json',
  },
  {
    name: 'validate-query',
    namespace: 'indices',
    description: 'Validates a potentially expensive query without executing it',
    method: 'POST',
    path: '/{index}/_validate/query',
    pathParams: [...withOptionalIndex],
    queryParams: [ignoreUnavailable, allowNoIndices, expandWildcards,
      { name: 'explain', type: 'boolean', description: 'If true, the response returns detailed information if an error has occurred' },
      { name: 'rewrite', type: 'boolean', description: 'If true, returns a more detailed explanation showing the actual Lucene query that will be executed' },
      { name: 'all_shards', type: 'boolean', description: 'If true, the validation is executed on all shards instead of one random shard per index' },
    ],
    body: z.object({
      query: z.record(z.string(), z.unknown()).optional().describe('Query to validate'),
    }),
    responseType: 'json',
  },
]
