/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { EsApiDefinition } from '../types.ts'

export const migrationDeprecationsApis: EsApiDefinition[] = [
 {
  name: "deprecations",
  namespace: "migration",
  description: "Get deprecation information.",
  method: "GET",
  path: "/_migration/deprecations",
 },
]
