/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { EsApiDefinition } from '../types.ts'

export const mlGetTrainedModelsStatsApis: EsApiDefinition[] = [
 {
  name: "get-trained-models-stats",
  namespace: "ml",
  description: "Get trained models usage info.",
  method: "GET",
  path: "/_ml/trained_models/_stats",
 },
]
