/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { EsApiDefinition } from '../types.ts'

export const mlPreviewDataFrameAnalyticsApis: EsApiDefinition[] = [
 {
  name: "preview-data-frame-analytics",
  namespace: "ml",
  description: "Preview features used by data frame analytics.",
  method: "GET",
  path: "/_ml/data_frame/analytics/_preview",
 },
]
