/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { EsApiDefinition } from '../types.ts'

export const searchableSnapshotsClearCacheApis: EsApiDefinition[] = [
 {
  name: "clear-cache",
  namespace: "searchable-snapshots",
  description: "Clear the cache.",
  method: "POST",
  path: "/_searchable_snapshots/cache/clear",
 },
]
