/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { EsApiDefinition } from '../types.ts'

export const snapshotStatusApis: EsApiDefinition[] = [
 {
  name: "status",
  namespace: "snapshot",
  description: "Get the snapshot status.",
  method: "GET",
  path: "/_snapshot/_status",
 },
]
