/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { KbApiDefinition } from '../types.ts'

export const dashboardsApis: KbApiDefinition[] = [
  {
    name: "get-dashboards",
    namespace: "dashboards",
    description: "Search dashboards",
    method: "GET",
    path: "/api/dashboards",
    queryParams: [
    { name: "page", type: "number", description: "The page of results to return. Defaults to `1`." },
    { name: "per_page", type: "number", description: "The number of results to return per page. Defaults to `20`." },
    { name: "query", type: "string", description: "Filters results by `title` and `description` using Elasticsearch [`simple_query_string`](https://www.elastic.co/docs/reference/query-languages/query-dsl/simple-query-string-query) syntax. Multi-word terms require all words to match." },
    { name: "tags", type: "string", description: "A tag ID to include. Accepts a single tag ID or multiple tag IDs. When multiple are specified, dashboards matching any of the tag IDs are included." },
    { name: "excluded_tags", type: "string", description: "A tag ID to exclude. Accepts a single tag ID or multiple tag IDs. When multiple are specified, dashboards matching any of the tag IDs are excluded." },
    ],
  },
  {
    name: "post-dashboards",
    namespace: "dashboards",
    description: "Create a dashboard",
    method: "POST",
    path: "/api/dashboards",
    bodyParams: [
    { name: "access_control", type: "object", description: "Access control settings for the dashboard.", required: true },
    { name: "description", type: "string", description: "A short description of the dashboard." },
    { name: "filters", type: "array", description: "Filters applied across all panels, including pinned panels." },
    { name: "options", type: "object", description: "Display and behavior settings for the dashboard.", required: true },
    { name: "panels", type: "array", description: "Panels and sections in the dashboard. Each entry is either a panel (with a `type` and `config`) or a collapsible section (with a `title`, `collapsed` state, and nested `panels`)." },
    { name: "pinned_panels", type: "array", description: "An array of control panels and their state in the control group." },
    { name: "project_routing", type: "string", description: "Controls [cross-project search](https://www.elastic.co/docs/explore-analyze/cross-project-search/cross-project-search-project-routing) behavior for this dashboard (Serverless only). Set to `_alias:_origin` to scope data to the current project, or `_alias:*` to search across all projects. When omitted, the space default applies." },
    { name: "query", type: "object", description: "A search query consisting of an expression and its language. Supports KQL and Lucene syntax.", required: true },
    { name: "refresh_interval", type: "object", description: "Specifies the auto-refresh interval for the object.", required: true },
    { name: "tags", type: "array", description: "Tag IDs to associate with this dashboard." },
    { name: "time_range", type: "object", description: "Specifies the time range for a query.", required: true },
    { name: "title", type: "string", description: "A human-readable title for the dashboard.", required: true },
    ],
  },
  {
    name: "delete-dashboards-id",
    namespace: "dashboards",
    description: "Delete a dashboard",
    method: "DELETE",
    path: "/api/dashboards/{id}",
    pathParams: [
    { name: "id", description: "The dashboard ID, as returned by the create or search endpoints.", required: true },
    ],
  },
  {
    name: "get-dashboards-id",
    namespace: "dashboards",
    description: "Get a dashboard",
    method: "GET",
    path: "/api/dashboards/{id}",
    pathParams: [
    { name: "id", description: "The dashboard ID, as returned by the create or search endpoints.", required: true },
    ],
  },
  {
    name: "put-dashboards-id",
    namespace: "dashboards",
    description: "Upsert a dashboard",
    method: "PUT",
    path: "/api/dashboards/{id}",
    pathParams: [
    { name: "id", description: "The id parameter", required: true },
    ],
    bodyParams: [
    { name: "description", type: "string", description: "A short description of the dashboard." },
    { name: "filters", type: "array", description: "Filters applied across all panels, including pinned panels." },
    { name: "options", type: "object", description: "Display and behavior settings for the dashboard.", required: true },
    { name: "panels", type: "array", description: "Panels and sections in the dashboard. Each entry is either a panel (with a `type` and `config`) or a collapsible section (with a `title`, `collapsed` state, and nested `panels`)." },
    { name: "pinned_panels", type: "array", description: "An array of control panels and their state in the control group." },
    { name: "project_routing", type: "string", description: "Controls [cross-project search](https://www.elastic.co/docs/explore-analyze/cross-project-search/cross-project-search-project-routing) behavior for this dashboard (Serverless only). Set to `_alias:_origin` to scope data to the current project, or `_alias:*` to search across all projects. When omitted, the space default applies." },
    { name: "query", type: "object", description: "A search query consisting of an expression and its language. Supports KQL and Lucene syntax.", required: true },
    { name: "refresh_interval", type: "object", description: "Specifies the auto-refresh interval for the object.", required: true },
    { name: "tags", type: "array", description: "Tag IDs to associate with this dashboard." },
    { name: "time_range", type: "object", description: "Specifies the time range for a query.", required: true },
    { name: "title", type: "string", description: "A human-readable title for the dashboard.", required: true },
    ],
  },
]
