name: Auto PR
on:
  issues:
    types: [labeled]

permissions:
  contents: write
  pull-requests: write
  issues: read

jobs:
  auto-pr:
    if: startsWith(github.event.label.name, 'auto-pr')
    uses: elastic/clients-team-automations/.github/workflows/auto-pr.yml@e1f9f004bf69bc295529417b002270216be143e9
    with:
      issue_number: ${{ github.event.issue.number }}
      search_directory: packages
    secrets:
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      OPENROUTER_BASE_URL: ${{ secrets.OPENROUTER_BASE_URL }}
