---
name: docs-deploy

on:
  workflow_run:
    workflows: [docs-build]
    types: [completed]

permissions:
  contents: read
  deployments: write
  id-token: write
  pull-requests: write
  actions: read

jobs:
  deploy:
    uses: elastic/docs-actions/.github/workflows/docs-deploy.yml@b90052dbe6a4cdbc6e8c8ef17049a11e7d70ccf9 # v1
    with:
      enable-vale-linting: true
