---
name: docs-preview-cleanup

on:
  pull_request_target:
    types:
      - closed

permissions: {}

jobs:
  cleanup:
    uses: elastic/docs-actions/.github/workflows/docs-preview-cleanup.yml@b90052dbe6a4cdbc6e8c8ef17049a11e7d70ccf9 # v1
    permissions:
      contents: none
      id-token: write
      deployments: write
