---
name: docs-preview-cleanup

on:
  pull_request_target:
    types:
      - closed

permissions: {}

jobs:
  cleanup:
    uses: elastic/docs-actions/.github/workflows/docs-preview-cleanup.yml@725a8e00e524fa8486375385edf44de1acf07703 # v1
    permissions:
      contents: none
      id-token: write
      deployments: write
