---
name: docs-preview-cleanup

on:
  pull_request_target:
    types:
      - closed

permissions: {}

jobs:
  cleanup:
    uses: elastic/docs-actions/.github/workflows/docs-preview-cleanup.yml@72ba1080f7dd27a87a322ce3806d7f8a5fce1b09 # v1
    permissions:
      contents: none
      id-token: write
      deployments: write
