name: Performance

on:
  pull_request:
  push:
    branches:
      - main

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  perf:
    name: Startup time regression check
    permissions:
      contents: read
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max-old-space-size=6144
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: 24.x

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Install hyperfine
        run: sudo apt-get install -y hyperfine

      - name: Run perf check
        run: scripts/perf-check
